# Average Prices of EVs versus New Cars

https://caredge.com/guides/average-price-of-an-electric-car

In [1]:
from splinter import Browser
from bs4 import BeautifulSoup as soup
import pandas as pd
from datetime import date

In [2]:
# Set up Splinter
browser = Browser('chrome')

In [3]:
# Visit https://caredge.com/guides/average-price-of-an-electric-car
url = 'https://caredge.com/guides/average-price-of-an-electric-car'
browser.visit(url)

In [4]:
# Parse the website
html = browser.html
html_soup = soup(html, 'html.parser')

In [5]:
# Find the table
table = html_soup.find('table')

In [6]:
table

<table aria-label="EV prices - EV prices by month.csv" class="foo-table ninja_footable foo_table_108700 ninja_table_unique_id_1417532660_108700 ui table nt_type_legacy_table selectable striped vertical_centered footable-paging-right ninja_table_pro footable footable-1 footable-filtering footable-filtering-right footable-paging breakpoint-lg" data-filter-delay="1000" data-footable_id="108700" data-ninja_table_instance="ninja_table_instance_0" data-unique_identifier="ninja_table_unique_id_1417532660_108700" id="footable_108700" style=""><colgroup><col class="ninja_column_0"/><col class="ninja_column_1"/><col class="ninja_column_2"/><col class="ninja_column_3"/><col class="ninja_column_4"/><col class="ninja_column_5"/><col class="ninja_column_6"/><col class="ninja_column_7"/><col class="ninja_column_8"/><col class="ninja_column_9"/><col class="ninja_column_10"/><col class="ninja_column_11"/><col class="ninja_column_12"/><col class="ninja_column_13"/><col class="ninja_column_14"/><col class="ninja_column_15"/><col class="ninja_column_16"/><col class="ninja_column_17"/><col class="ninja_column_18"/><col class="ninja_column_19"/><col class="ninja_column_20"/><col class="ninja_column_21"/><col class="ninja_column_22"/><col class="ninja_column_23"/><col class="ninja_column_24"/><col class="ninja_column_25"/><col class="ninja_column_26"/><col class="ninja_column_27"/><col class="ninja_column_28"/><col class="ninja_column_29"/><col class="ninja_column_30"/><col class="ninja_column_31"/><col class="ninja_column_32"/><col class="ninja_column_33"/><col class="ninja_column_34"/><col class="ninja_column_35"/><col class="ninja_column_36"/><col class="ninja_column_37"/><col class="ninja_column_38"/><col class="ninja_column_39"/></colgroup><thead><tr class="footable-filtering"><th colspan="40" scope="row"><form class="form-inline"><div class="form-group footable-filtering-search"><label class="sr-only">Search</label><div class="input-group"><input aria-label="Search in Table" autocapitalize="off" autocorrect="off" class="form-control" placeholder="Search" spellcheck="false" type="text"/><div class="input-group-btn"><button aria-label="Search" class="btn btn-primary" type="submit" value="Search"><span class="fooicon fooicon-search"></span></button><button aria-label="Search in" class="btn btn-default dropdown-toggle" type="button" value="Search in"><span class="caret"></span></button><ul aria-labelledby="ninja_drop_down_id_footable_108700" class="dropdown-menu dropdown-menu-right" role="group"><li class="dropdown-header" id="ninja_drop_down_id_footable_108700">Search in</li><li><a class="checkbox"><label><input autocapitalize="off" autocorrect="off" checked="checked" spellcheck="false" type="checkbox"/></label></a></li><li><a class="checkbox"><label><input autocapitalize="off" autocorrect="off" checked="checked" spellcheck="false" type="checkbox"/>1-2020</label></a></li><li><a class="checkbox"><label><input autocapitalize="off" autocorrect="off" checked="checked" spellcheck="false" type="checkbox"/>2-2020</label></a></li><li><a class="checkbox"><label><input autocapitalize="off" autocorrect="off" checked="checked" spellcheck="false" type="checkbox"/>3-2020</label></a></li><li><a class="checkbox"><label><input autocapitalize="off" autocorrect="off" checked="checked" spellcheck="false" type="checkbox"/>4-2020</label></a></li><li><a class="checkbox"><label><input autocapitalize="off" autocorrect="off" checked="checked" spellcheck="false" type="checkbox"/>5-2020</label></a></li><li><a class="checkbox"><label><input autocapitalize="off" autocorrect="off" checked="checked" spellcheck="false" type="checkbox"/>6-2020</label></a></li><li><a class="checkbox"><label><input autocapitalize="off" autocorrect="off" checked="checked" spellcheck="false" type="checkbox"/>7-2020</label></a></li><li><a class="checkbox"><label><input autocapitalize="off" autocorrect="off" checked="checked" spellcheck="false" type="checkbox"/>8-2020</label></a></li><li><a class="checkbox"><label><input autocapitalize="off" autocorrect="off" checked="checked" spellcheck="false" type="checkbox"/>9-2020</label></a></li><li><a class="checkbox"><label><input autocapitalize="off" autocorrect="off" checked="checked" spellcheck="false" type="checkbox"/>10-2020</label></a></li><li><a class="checkbox"><label><input autocapitalize="off" autocorrect="off" checked="checked" spellcheck="false" type="checkbox"/>11-2020</label></a></li><li><a class="checkbox"><label><input autocapitalize="off" autocorrect="off" checked="checked" spellcheck="false" type="checkbox"/>12-2020</label></a></li><li><a class="checkbox"><label><input autocapitalize="off" autocorrect="off" checked="checked" spellcheck="false" type="checkbox"/>1-2021</label></a></li><li><a class="checkbox"><label><input autocapitalize="off" autocorrect="off" checked="checked" spellcheck="false" type="checkbox"/>2-2021</label></a></li><li><a class="checkbox"><label><input autocapitalize="off" autocorrect="off" checked="checked" spellcheck="false" type="checkbox"/>3-2021</label></a></li><li><a class="checkbox"><label><input autocapitalize="off" autocorrect="off" checked="checked" spellcheck="false" type="checkbox"/>4-2021</label></a></li><li><a class="checkbox"><label><input autocapitalize="off" autocorrect="off" checked="checked" spellcheck="false" type="checkbox"/>5-2021</label></a></li><li><a class="checkbox"><label><input autocapitalize="off" autocorrect="off" checked="checked" spellcheck="false" type="checkbox"/>6-2021</label></a></li><li><a class="checkbox"><label><input autocapitalize="off" autocorrect="off" checked="checked" spellcheck="false" type="checkbox"/>7-2021</label></a></li><li><a class="checkbox"><label><input autocapitalize="off" autocorrect="off" checked="checked" spellcheck="false" type="checkbox"/>8-2021</label></a></li><li><a class="checkbox"><label><input autocapitalize="off" autocorrect="off" checked="checked" spellcheck="false" type="checkbox"/>9-2021</label></a></li><li><a class="checkbox"><label><input autocapitalize="off" autocorrect="off" checked="checked" spellcheck="false" type="checkbox"/>10-2021</label></a></li><li><a class="checkbox"><label><input autocapitalize="off" autocorrect="off" checked="checked" spellcheck="false" type="checkbox"/>11-2021</label></a></li><li><a class="checkbox"><label><input autocapitalize="off" autocorrect="off" checked="checked" spellcheck="false" type="checkbox"/>12-2021</label></a></li><li><a class="checkbox"><label><input autocapitalize="off" autocorrect="off" checked="checked" spellcheck="false" type="checkbox"/>1-2022</label></a></li><li><a class="checkbox"><label><input autocapitalize="off" autocorrect="off" checked="checked" spellcheck="false" type="checkbox"/>2-2022</label></a></li><li><a class="checkbox"><label><input autocapitalize="off" autocorrect="off" checked="checked" spellcheck="false" type="checkbox"/>3-2022</label></a></li><li><a class="checkbox"><label><input autocapitalize="off" autocorrect="off" checked="checked" spellcheck="false" type="checkbox"/>4-2022</label></a></li><li><a class="checkbox"><label><input autocapitalize="off" autocorrect="off" checked="checked" spellcheck="false" type="checkbox"/>5-2022</label></a></li><li><a class="checkbox"><label><input autocapitalize="off" autocorrect="off" checked="checked" spellcheck="false" type="checkbox"/>June 2022</label></a></li><li><a class="checkbox"><label><input autocapitalize="off" autocorrect="off" checked="checked" spellcheck="false" type="checkbox"/>July 2022</label></a></li><li><a class="checkbox"><label><input autocapitalize="off" autocorrect="off" checked="checked" spellcheck="false" type="checkbox"/>August 2022</label></a></li><li><a class="checkbox"><label><input autocapitalize="off" autocorrect="off" checked="checked" spellcheck="false" type="checkbox"/>September 2022</label></a></li><li><a class="checkbox"><label><input autocapitalize="off" autocorrect="off" checked="checked" spellcheck="false" type="checkbox"/>October 2022</label></a></li><li><a class="checkbox"><label><input autocapitalize="off" autocorrect="off" checked="checked" spellcheck="false" type="checkbox"/>November 2022</label></a></li><li><a class="checkbox"><label><input autocapitalize="off" autocorrect="off" checked="checked" spellcheck="false" type="checkbox"/>December 2022</label></a></li><li><a class="checkbox"><label><input autocapitalize="off" autocorrect="off" checked="checked" spellcheck="false" type="checkbox"/>January 2023</label></a></li><li><a class="checkbox"><label><input autocapitalize="off" autocorrect="off" checked="checked" spellcheck="false" type="checkbox"/>February 2023</label></a></li><li><a class="checkbox"><label><input autocapitalize="off" autocorrect="off" checked="checked" spellcheck="false" type="checkbox"/>March 2023</label></a></li></ul></div></div></div></form></th></tr><tr class="footable-header"><th class="ninja_column_0 ninja_clmn_nm_ninja_column_1 footable-sortable footable-first-visible" scope="col" style="display: table-cell;"><span class="fooicon fooicon-sort"></span></th><th class="ninja_column_1 ninja_clmn_nm_122 footable-sortable" scope="col" style="display: table-cell;">1-2020<span class="fooicon fooicon-sort"></span></th><th class="ninja_column_2 ninja_clmn_nm_222 footable-sortable" scope="col" style="display: table-cell;">2-2020<span class="fooicon fooicon-sort"></span></th><th class="ninja_column_3 ninja_clmn_nm_322 footable-sortable" scope="col" style="display: table-cell;">3-2020<span class="fooicon fooicon-sort"></span></th><th class="ninja_column_4 ninja_clmn_nm_422 footable-sortable" scope="col" style="display: table-cell;">4-2020<span class="fooicon fooicon-sort"></span></th><th class="ninja_column_5 ninja_clmn_nm_522 footable-sortable" scope="col" style="display: table-cell;">5-2020<span class="fooicon fooicon-sort"></span></th><th class="ninja_column_6 ninja_clmn_nm_622 footable-sortable" scope="col" style="display: table-cell;">6-2020<span class="fooicon fooicon-sort"></span></th><th class="ninja_column_7 ninja_clmn_nm_722 footable-sortable" scope="col" style="display: table-cell;">7-2020<span class="fooicon fooicon-sort"></span></th><th class="ninja_column_8 ninja_clmn_nm_822 footable-sortable" scope="col" style="display: table-cell;">8-2020<span class="fooicon fooicon-sort"></span></th><th class="ninja_column_9 ninja_clmn_nm_922 footable-sortable" scope="col" style="display: table-cell;">9-2020<span class="fooicon fooicon-sort"></span></th><th class="ninja_column_10 ninja_clmn_nm_122_1 footable-sortable" scope="col" style="display: table-cell;">10-2020<span class="fooicon fooicon-sort"></span></th><th class="ninja_column_11 ninja_clmn_nm_1122 footable-sortable" scope="col" style="display: table-cell;">11-2020<span class="fooicon fooicon-sort"></span></th><th class="ninja_column_12 ninja_clmn_nm_1222 footable-sortable" scope="col" style="display: table-cell;">12-2020<span class="fooicon fooicon-sort"></span></th><th class="ninja_column_13 ninja_clmn_nm_1221 footable-sortable" scope="col" style="display: table-cell;">1-2021<span class="fooicon fooicon-sort"></span></th><th class="ninja_column_14 ninja_clmn_nm_2221 footable-sortable" scope="col" style="display: table-cell;">2-2021<span class="fooicon fooicon-sort"></span></th><th class="ninja_column_15 ninja_clmn_nm_3221 footable-sortable" scope="col" style="display: table-cell;">3-2021<span class="fooicon fooicon-sort"></span></th><th class="ninja_column_16 ninja_clmn_nm_4221 footable-sortable" scope="col" style="display: table-cell;">4-2021<span class="fooicon fooicon-sort"></span></th><th class="ninja_column_17 ninja_clmn_nm_5221 footable-sortable" scope="col" style="display: table-cell;">5-2021<span class="fooicon fooicon-sort"></span></th><th class="ninja_column_18 ninja_clmn_nm_6221 footable-sortable" scope="col" style="display: table-cell;">6-2021<span class="fooicon fooicon-sort"></span></th><th class="ninja_column_19 ninja_clmn_nm_7221 footable-sortable" scope="col" style="display: table-cell;">7-2021<span class="fooicon fooicon-sort"></span></th><th class="ninja_column_20 ninja_clmn_nm_8221 footable-sortable" scope="col" style="display: table-cell;">8-2021<span class="fooicon fooicon-sort"></span></th><th class="ninja_column_21 ninja_clmn_nm_9221 footable-sortable" scope="col" style="display: table-cell;">9-2021<span class="fooicon fooicon-sort"></span></th><th class="ninja_column_22 ninja_clmn_nm_1221_1 footable-sortable" scope="col" style="display: table-cell;">10-2021<span class="fooicon fooicon-sort"></span></th><th class="ninja_column_23 ninja_clmn_nm_11221 footable-sortable" scope="col" style="display: table-cell;">11-2021<span class="fooicon fooicon-sort"></span></th><th class="ninja_column_24 ninja_clmn_nm_12221 footable-sortable" scope="col" style="display: table-cell;">12-2021<span class="fooicon fooicon-sort"></span></th><th class="ninja_column_25 ninja_clmn_nm_1222_1 footable-sortable" scope="col" style="display: table-cell;">1-2022<span class="fooicon fooicon-sort"></span></th><th class="ninja_column_26 ninja_clmn_nm_2222 footable-sortable" scope="col" style="display: table-cell;">2-2022<span class="fooicon fooicon-sort"></span></th><th class="ninja_column_27 ninja_clmn_nm_3222 footable-sortable" scope="col" style="display: table-cell;">3-2022<span class="fooicon fooicon-sort"></span></th><th class="ninja_column_28 ninja_clmn_nm_4222 footable-sortable" scope="col" style="display: table-cell;">4-2022<span class="fooicon fooicon-sort"></span></th><th class="ninja_column_29 ninja_clmn_nm_5222 footable-sortable" scope="col" style="display: table-cell;">5-2022<span class="fooicon fooicon-sort"></span></th><th class="ninja_column_30 ninja_clmn_nm_june222 footable-sortable" scope="col" style="display: table-cell;">June 2022<span class="fooicon fooicon-sort"></span></th><th class="ninja_column_31 ninja_clmn_nm_july222 footable-sortable" scope="col" style="display: table-cell;">July 2022<span class="fooicon fooicon-sort"></span></th><th class="ninja_column_32 ninja_clmn_nm_august222 footable-sortable" scope="col" style="display: table-cell;">August 2022<span class="fooicon fooicon-sort"></span></th><th class="ninja_column_33 ninja_clmn_nm_september_2022 footable-sortable" scope="col" style="display: table-cell;">September 2022<span class="fooicon fooicon-sort"></span></th><th class="ninja_column_34 ninja_clmn_nm_october_2022 footable-sortable" scope="col" style="display: table-cell;">October 2022<span class="fooicon fooicon-sort"></span></th><th class="ninja_column_35 ninja_clmn_nm_november_2022 footable-sortable" scope="col" style="display: table-cell;">November 2022<span class="fooicon fooicon-sort"></span></th><th class="ninja_column_36 ninja_clmn_nm_december_2022 footable-sortable" scope="col" style="display: table-cell;">December 2022<span class="fooicon fooicon-sort"></span></th><th class="ninja_column_37 ninja_clmn_nm_january_2023 footable-sortable" scope="col" style="display: table-cell;">January 2023<span class="fooicon fooicon-sort"></span></th><th class="ninja_column_38 ninja_clmn_nm_february_2023 footable-sortable" scope="col" style="display: table-cell;">February 2023<span class="fooicon fooicon-sort"></span></th><th class="ninja_column_39 ninja_clmn_nm_march_2023 footable-sortable footable-last-visible" scope="col" style="display: table-cell;">March 2023<span class="fooicon fooicon-sort"></span></th></tr></thead><tbody><tr class="ninja_table_row_0 nt_row_id_470" data-row_id="470"><td class="ninja_column_0 ninja_clmn_nm_ninja_column_1 footable-first-visible" style="display: table-cell;">Average EV Price</td><td class="ninja_column_1 ninja_clmn_nm_122" style="display: table-cell;">$54,669</td><td class="ninja_column_2 ninja_clmn_nm_222" style="display: table-cell;">$56,326</td><td class="ninja_column_3 ninja_clmn_nm_322" style="display: table-cell;">$56,059</td><td class="ninja_column_4 ninja_clmn_nm_422" style="display: table-cell;">$57,757</td><td class="ninja_column_5 ninja_clmn_nm_522" style="display: table-cell;">$58,863</td><td class="ninja_column_6 ninja_clmn_nm_622" style="display: table-cell;">$57,480</td><td class="ninja_column_7 ninja_clmn_nm_722" style="display: table-cell;">$57,346</td><td class="ninja_column_8 ninja_clmn_nm_822" style="display: table-cell;">$57,346</td><td class="ninja_column_9 ninja_clmn_nm_922" style="display: table-cell;">$54,381</td><td class="ninja_column_10 ninja_clmn_nm_122_1" style="display: table-cell;">$52,947</td><td class="ninja_column_11 ninja_clmn_nm_1122" style="display: table-cell;">$53,117</td><td class="ninja_column_12 ninja_clmn_nm_1222" style="display: table-cell;">$53,811</td><td class="ninja_column_13 ninja_clmn_nm_1221" style="display: table-cell;">$57,750</td><td class="ninja_column_14 ninja_clmn_nm_2221" style="display: table-cell;">$57,491</td><td class="ninja_column_15 ninja_clmn_nm_3221" style="display: table-cell;">$56,503</td><td class="ninja_column_16 ninja_clmn_nm_4221" style="display: table-cell;">$56,059</td><td class="ninja_column_17 ninja_clmn_nm_5221" style="display: table-cell;">$56,140</td><td class="ninja_column_18 ninja_clmn_nm_6221" style="display: table-cell;">$58,914</td><td class="ninja_column_19 ninja_clmn_nm_7221" style="display: table-cell;">$56,110</td><td class="ninja_column_20 ninja_clmn_nm_8221" style="display: table-cell;">$57,540</td><td class="ninja_column_21 ninja_clmn_nm_9221" style="display: table-cell;">$56,312</td><td class="ninja_column_22 ninja_clmn_nm_1221_1" style="display: table-cell;">$55,625</td><td class="ninja_column_23 ninja_clmn_nm_11221" style="display: table-cell;">$56,437</td><td class="ninja_column_24 ninja_clmn_nm_12221" style="display: table-cell;">$63,821</td><td class="ninja_column_25 ninja_clmn_nm_1222_1" style="display: table-cell;">$62,876</td><td class="ninja_column_26 ninja_clmn_nm_2222" style="display: table-cell;">$64,807</td><td class="ninja_column_27 ninja_clmn_nm_3222" style="display: table-cell;">$66,386</td><td class="ninja_column_28 ninja_clmn_nm_4222" style="display: table-cell;">$65,094</td><td class="ninja_column_29 ninja_clmn_nm_5222" style="display: table-cell;">$64,553</td><td class="ninja_column_30 ninja_clmn_nm_june222" style="display: table-cell;">$66,997</td><td class="ninja_column_31 ninja_clmn_nm_july222" style="display: table-cell;">$66,645</td><td class="ninja_column_32 ninja_clmn_nm_august222" style="display: table-cell;">$66,524</td><td class="ninja_column_33 ninja_clmn_nm_september_2022" style="display: table-cell;">$65,291</td><td class="ninja_column_34 ninja_clmn_nm_october_2022" style="display: table-cell;">$64,249</td><td class="ninja_column_35 ninja_clmn_nm_november_2022" style="display: table-cell;">$65,041</td><td class="ninja_column_36 ninja_clmn_nm_december_2022" style="display: table-cell;">$61,448</td><td class="ninja_column_37 ninja_clmn_nm_january_2023" style="display: table-cell;">$58,725</td><td class="ninja_column_38 ninja_clmn_nm_february_2023" style="display: table-cell;">$58,385</td><td class="ninja_column_39 ninja_clmn_nm_march_2023 footable-last-visible" style="display: table-cell;">$58,940</td></tr><tr class="ninja_table_row_1 nt_row_id_471" data-row_id="471"><td class="ninja_column_0 ninja_clmn_nm_ninja_column_1 footable-first-visible" style="display: table-cell;">New Car Average</td><td class="ninja_column_1 ninja_clmn_nm_122" style="display: table-cell;">$38,747</td><td class="ninja_column_2 ninja_clmn_nm_222" style="display: table-cell;">$38,550</td><td class="ninja_column_3 ninja_clmn_nm_322" style="display: table-cell;">$38,812</td><td class="ninja_column_4 ninja_clmn_nm_422" style="display: table-cell;">$39,904</td><td class="ninja_column_5 ninja_clmn_nm_522" style="display: table-cell;">$39,138</td><td class="ninja_column_6 ninja_clmn_nm_622" style="display: table-cell;">$39,731</td><td class="ninja_column_7 ninja_clmn_nm_722" style="display: table-cell;">$39,512</td><td class="ninja_column_8 ninja_clmn_nm_822" style="display: tab

In [27]:
df = pd.DataFrame(columns=['Dates', 'Average EV Price', 'New Car Average'])

df

Empty DataFrame
Columns: [Dates, Average EV Price, New Car Average]
Index: []

In [28]:
dates = []
avg_ev = []
avg_new = []

for row in table.thead.find_all('th'):
    dates.append(row.text.strip())

dates.pop(0)

avg_ev_costs = table.tbody.find('tr', class_="ninja_table_row_0 nt_row_id_470")
for row in avg_ev_costs.find_all('td'):
    avg_ev.append(row.text.strip())

avg_new_costs = table.tbody.find('tr', class_="ninja_table_row_1 nt_row_id_471")
for row in avg_new_costs.find_all('td'):
    avg_new.append(row.text.strip())

In [29]:
df['Dates'] = dates
df['Average EV Price'] = avg_ev
df['New Car Average'] = avg_new

df

             Dates  Average EV Price  New Car Average
0                   Average EV Price  New Car Average
1           1-2020           $54,669          $38,747
2           2-2020           $56,326          $38,550
3           3-2020           $56,059          $38,812
4           4-2020           $57,757          $39,904
5           5-2020           $58,863          $39,138
6           6-2020           $57,480          $39,731
7           7-2020           $57,346          $39,512
8           8-2020           $57,346          $39,571
9           9-2020           $54,381          $40,159
10         10-2020           $52,947          $40,770
11         11-2020           $53,117          $40,937
12         12-2020           $53,811          $41,335
13          1-2021           $57,750          $41,248
14          2-2021           $57,491          $41,366
15          3-2021           $56,503          $40,680
16          4-2021           $56,059          $41,172
17          5-2021           $56,140          $41,534
18          6-2021           $58,914          $42,633
19          7-2021           $56,110          $43,056
20          8-2021           $57,540          $43,418
21          9-2021           $56,312          $45,031
22         10-2021           $55,625          $46,026
23         11-2021           $56,437          $46,329
24         12-2021           $63,821          $47,243
25          1-2022           $62,876          $46,404
26          2-2022           $64,807          $46,082
27          3-2022           $66,386          $46,223
28          4-2022           $65,094          $46,676
29          5-2022           $64,553          $47,275
30       June 2022           $66,997          $48,043
31       July 2022           $66,645          $48,182
32     August 2022           $66,524          $48,301
33  September 2022           $65,291          $48,094
34    October 2022           $64,249          $48,281
35   November 2022           $65,041          $48,681
36   December 2022           $61,448          $49,507
37    January 2023           $58,725          $49,388
38   February 2023           $58,385          $48,763
39      March 2023           $58,940          $48,008

In [10]:
# Quit the browsing session
browser.quit()

In [30]:
df.dtypes

Dates               object
Average EV Price    object
New Car Average     object
dtype: object

In [35]:
df_cleaned.drop(labels=[0], axis=0, inplace=True)

KeyError: '[0] not found in axis'

In [47]:
df_cleaned = df
df_cleaned['Dates'] = pd.to_datetime(df_cleaned['Dates'], format=None)
df_cleaned['Dates'] = df_cleaned['Dates'].dt.strftime('%Y-%m')

In [48]:
df_cleaned

      Dates Average EV Price New Car Average
1   2020-01          $54,669         $38,747
2   2020-02          $56,326         $38,550
3   2020-03          $56,059         $38,812
4   2020-04          $57,757         $39,904
5   2020-05          $58,863         $39,138
6   2020-06          $57,480         $39,731
7   2020-07          $57,346         $39,512
8   2020-08          $57,346         $39,571
9   2020-09          $54,381         $40,159
10  2020-10          $52,947         $40,770
11  2020-11          $53,117         $40,937
12  2020-12          $53,811         $41,335
13  2021-01          $57,750         $41,248
14  2021-02          $57,491         $41,366
15  2021-03          $56,503         $40,680
16  2021-04          $56,059         $41,172
17  2021-05          $56,140         $41,534
18  2021-06          $58,914         $42,633
19  2021-07          $56,110         $43,056
20  2021-08          $57,540         $43,418
21  2021-09          $56,312         $45,031
22  2021-10          $55,625         $46,026
23  2021-11          $56,437         $46,329
24  2021-12          $63,821         $47,243
25  2022-01          $62,876         $46,404
26  2022-02          $64,807         $46,082
27  2022-03          $66,386         $46,223
28  2022-04          $65,094         $46,676
29  2022-05          $64,553         $47,275
30  2022-06          $66,997         $48,043
31  2022-07          $66,645         $48,182
32  2022-08          $66,524         $48,301
33  2022-09          $65,291         $48,094
34  2022-10          $64,249         $48,281
35  2022-11          $65,041         $48,681
36  2022-12          $61,448         $49,507
37  2023-01          $58,725         $49,388
38  2023-02          $58,385         $48,763
39  2023-03          $58,940         $48,008

In [53]:
df_cleaned.columns

Index(['index', 'Dates', 'Average EV Price', 'New Car Average'], dtype='object')

In [54]:
df_cleaned['Average EV Price'] = df_cleaned['Average EV Price'].str.replace('$', '')
df_cleaned['Average EV Price'] = df_cleaned['Average EV Price'].str.replace(',', '')

/Users/seanguzman/opt/anaconda3/envs/pythondata/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  """Entry point for launching an IPython kernel.

In [55]:
df_cleaned['New Car Average'] = df_cleaned['New Car Average'].str.replace('$', '')
df_cleaned['New Car Average'] = df_cleaned['New Car Average'].str.replace(',', '')

/Users/seanguzman/opt/anaconda3/envs/pythondata/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  """Entry point for launching an IPython kernel.

In [56]:
df_cleaned['New Car Average'] = df_cleaned['New Car Average'].astype(int)
df_cleaned['Average EV Price'] = df_cleaned['Average EV Price'].astype(int)

In [57]:
df_cleaned.dtypes

index                int64
Dates               object
Average EV Price     int64
New Car Average      int64
dtype: object

In [58]:
df_cleaned

    index    Dates  Average EV Price  New Car Average
0       1  2020-01             54669            38747
1       2  2020-02             56326            38550
2       3  2020-03             56059            38812
3       4  2020-04             57757            39904
4       5  2020-05             58863            39138
5       6  2020-06             57480            39731
6       7  2020-07             57346            39512
7       8  2020-08             57346            39571
8       9  2020-09             54381            40159
9      10  2020-10             52947            40770
10     11  2020-11             53117            40937
11     12  2020-12             53811            41335
12     13  2021-01             57750            41248
13     14  2021-02             57491            41366
14     15  2021-03             56503            40680
15     16  2021-04             56059            41172
16     17  2021-05             56140            41534
17     18  2021-06             58914            42633
18     19  2021-07             56110            43056
19     20  2021-08             57540            43418
20     21  2021-09             56312            45031
21     22  2021-10             55625            46026
22     23  2021-11             56437            46329
23     24  2021-12             63821            47243
24     25  2022-01             62876            46404
25     26  2022-02             64807            46082
26     27  2022-03             66386            46223
27     28  2022-04             65094            46676
28     29  2022-05             64553            47275
29     30  2022-06             66997            48043
30     31  2022-07             66645            48182
31     32  2022-08             66524            48301
32     33  2022-09             65291            48094
33     34  2022-10             64249            48281
34     35  2022-11             65041            48681
35     36  2022-12             61448            49507
36     37  2023-01             58725            49388
37     38  2023-02             58385            48763
38     39  2023-03             58940            48008

In [50]:
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi
uri = "mongodb+srv://seanguzman:Rutgers123!@atlascluster.hbnzjsz.mongodb.net/?retryWrites=true&w=majority"
# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))
# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

Pinged your deployment. You successfully connected to MongoDB!

In [54]:
db = client["mydatabase"]

In [55]:
db

Database(MongoClient(host=['ac-xlr5oxk-shard-00-00.hbnzjsz.mongodb.net:27017', 'ac-xlr5oxk-shard-00-01.hbnzjsz.mongodb.net:27017', 'ac-xlr5oxk-shard-00-02.hbnzjsz.mongodb.net:27017'], document_class=dict, tz_aware=False, connect=True, retrywrites=True, w='majority', authsource='admin', replicaset='atlas-a7nxeh-shard-0', ssl=True, server_api=<pymongo.server_api.ServerApi object at 0x7feba8f95410>), 'mydatabase')

In [56]:
print(client.list_database_names())

['__realm_sync_647fd50aabe91e708867b245', 'mydatabase', 'admin', 'local']

In [59]:
db = client['mydatabase']
collection = db['avg_price_ev_new']
df.reset_index(inplace=True)
data_dict = df.to_dict("records")
# Insert collection
collection.insert_many(data_dict)