In [34]:
# Import Dependencies
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [35]:
# Import our data into pandas from CSV
car_brands = 'EVs for each Car Brand by Year.xlsx'
car_brands_df = pd.read_excel(car_brands)

car_brands_df.head()

,Manufacturer,1991,1992,1993,1994,1995,1996,1997,1998,1999,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,Total
0,Acura,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,NaN,1.0,3.0,3.0,3.0,3.0,1.0,1.0,18.0
1,Audi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.0,7.0,7.0,4.0,1.0,7.0,15.0,28.0,37.0,118.0
2,Bentley Motors,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,3.0,0.0,NaN,NaN,NaN,1.0,1.0,1.0,20.0
3,BMW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.0,6.0,5.0,7.0,9.0,9.0,10.0,22.0,28.0,110.0
4,Buick,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,3.0,2.0,NaN,1.0,1.0,NaN,NaN,NaN,23.0

In [36]:
car_brands_df.replace('', np.nan, inplace=True)
car_brands_df

,Manufacturer,1991,1992,1993,1994,1995,1996,1997,1998,1999,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,Total
0,Acura,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,NaN,1.0,3.0,3.0,3.0,3.0,1.0,1.0,18.0
1,Audi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.0,7.0,7.0,4.0,1.0,7.0,15.0,28.0,37.0,118.0
2,Bentley Motors,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,3.0,0.0,NaN,NaN,NaN,1.0,1.0,1.0,20.0
3,BMW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.0,6.0,5.0,7.0,9.0,9.0,10.0,22.0,28.0,110.0
4,Buick,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,3.0,2.0,NaN,1.0,1.0,NaN,NaN,NaN,23.0
5,BYD Motors,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN,2.0
6,Cadillac,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,2.0,1.0,1.0,1.0,NaN,NaN,2.0,2.0,31.0
7,Chevrolet,1.0,2.0,3.0,NaN,NaN,NaN,1.0,4.0,4.0,...,24.0,30.0,27.0,24.0,31.0,21.0,17.0,12.0,16.0,366.0
8,Chrysler,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,...,3.0,5.0,5.0,4.0,3.0,3.0,1.0,1.0,1.0,63.0
9,Coda Automotive,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
10,Dodge,NaN,2.0,2.0,3.0,7.0,5.0,NaN,1.0,4.0,...,7.0,6.0,5.0,2.0,4.0,3.0,NaN,NaN,NaN,128.0
11,Ferrari,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,1.0,2.0,4.0
12,Fiat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,1.0,NaN,1.0,1.0,1.0,NaN,NaN,NaN,6.0
13,Fisker Automotive,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
14,Ford,1.0,1.0,2.0,2.0,5.0,6.0,14.0,13.0,19.0,...,48.0,38.0,25.0,22.0,32.0,35.0,44.0,33.0,32.0,525.0
15,General Motors EV,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0
16,GMC,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,...,19.0,19.0,13.0,20.0,23.0,16.0,15.0,11.0,12.0,250.0
17,Honda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,...,8.0,5.0,2.0,2.0,4.0,6.0,6.0,7.0,5.0,97.0
18,HUMMER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
19,Hyundai,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,2.0,3.0,8.0,7.0,9.0,9.0,13.0,19.0,74.0
20,Infiniti,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,4.0,4.0,5.0,3.0,NaN,NaN,NaN,NaN,22.0
21,Jaguar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.0,5.0,NaN,4.0,5.0,6.0,1.0,4.0,3.0,38.0
22,Jeep,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,3.0,3.0,4.0,3.0,2.0,3.0,3.0,6.0,38.0
23,Karma,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,1.0,1.0,2.0,NaN,5.0
24,Kia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,2.0,1.0,6.0,7.0,8.0,7.0,6.0,11.0,52.0
25,Land Rover,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,3.0,NaN,1.0,1.0,5.0,9.0,11.0,15.0,49.0
26,Lexus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.0,7.0,7.0,5.0,8.0,9.0,9.0,9.0,9.0,87.0
27,Lincoln,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,28.0
28,Lucid,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,6.0
29,Mazda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,13.0
30,McLaren,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0
31,Mercedes-Benz,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.0,8.0,8.0,7.0,6.0,11.0,13.0,25.0,33.0,146.0
32,Mercury,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.0
33,Mini,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,1.0,2.0,2.0,2.0,8.0
34,Mitsubishi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,12.0
35,Nissan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,...,4.0,4.0,5.0,5.0,6.0,7.0,3.0,3.0,3.0,75.0
36,Plymouth,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0
37,Polestar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0
38,Porsche,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,3.0,2.0,4.0,7.0,7.0,13.0,19.0,17.0,78.0
39,QUANTUM-PROCON,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0
40,Ram,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.0,6.0,6.0,6.0,5.0,7.0,5.0,5.0,5.0,56.0
41,Rivian,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN
42,Saab,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
43,Saturn,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0
44,Scion,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
45,Smart,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,1.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,10.0
46,Solectria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0
47,Subaru,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,1.0,1.0,NaN,NaN,1.0,1.0,1.0,NaN,6.0
48,Tesla,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,1.0,4.0,15.0,10.0,17.0,16.0,9.0,13.0,91.0
49,Toyota,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,...,10.0,10.0,11.0,14.0,13.0,14.0,14.0,19.0,22.0,192.0
50,Vehicle Production Group,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
51,Volkswagen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,3.0,2.0,1.0,NaN,1.0,1.0,2.0,4.0,22.0
52,Volvo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,2.0,3.0,4.0,5.0,6.0,12.0,33.0
53,"Wheego Electric Cars, Inc.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
54,Total,2.0,5.0,7.0,5.0,13.0,12.0,17.0,25.0,43.0,...,195.0,191.0,155.0,183.0,203.0,220.0,227.0,261.0,325.0,2974.0

In [37]:
car_brands_df = car_brands_df.fillna(0)
car_brands_df.head()

,Manufacturer,1991,1992,1993,1994,1995,1996,1997,1998,1999,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,Total
0,Acura,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,0.0,1.0,3.0,3.0,3.0,3.0,1.0,1.0,18.0
1,Audi,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.0,7.0,7.0,4.0,1.0,7.0,15.0,28.0,37.0,118.0
2,Bentley Motors,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,3.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,20.0
3,BMW,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.0,6.0,5.0,7.0,9.0,9.0,10.0,22.0,28.0,110.0
4,Buick,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,3.0,2.0,0.0,1.0,1.0,0.0,0.0,0.0,23.0

In [38]:
for i in car_brands_df.columns:
    try:
        car_brands_df[[i]] = car_brands_df[[i]].astype(int)
    except:
        pass

car_brands_df.head()

,Manufacturer,1991,1992,1993,1994,1995,1996,1997,1998,1999,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,Total
0,Acura,0,0,0,0,0,0,0,0,0,...,2,0,1,3,3,3,3,1,1,18
1,Audi,0,0,0,0,0,0,0,0,0,...,6,7,7,4,1,7,15,28,37,118
2,Bentley Motors,0,0,0,0,0,0,0,0,0,...,4,3,0,0,0,0,1,1,1,20
3,BMW,0,0,0,0,0,0,0,0,0,...,6,6,5,7,9,9,10,22,28,110
4,Buick,0,0,0,0,0,0,0,0,0,...,1,3,2,0,1,1,0,0,0,23

In [39]:
car_brands_df.drop(["Total"], axis = 1)
car_brands_df.head()

,Manufacturer,1991,1992,1993,1994,1995,1996,1997,1998,1999,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,Total
0,Acura,0,0,0,0,0,0,0,0,0,...,2,0,1,3,3,3,3,1,1,18
1,Audi,0,0,0,0,0,0,0,0,0,...,6,7,7,4,1,7,15,28,37,118
2,Bentley Motors,0,0,0,0,0,0,0,0,0,...,4,3,0,0,0,0,1,1,1,20
3,BMW,0,0,0,0,0,0,0,0,0,...,6,6,5,7,9,9,10,22,28,110
4,Buick,0,0,0,0,0,0,0,0,0,...,1,3,2,0,1,1,0,0,0,23